### ISSUE TITLE
Error loading modules in OBI using TBC

### ISSUE THREAD

**Issue by DanBerrios** [obi-ontology/obi#940]
Many of the modules are now throwing this error on load:

eclipse.buildId=unknown
java.version=1.8.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.topbraid.eclipsex
Error
Mon Jun 04 09:06:17 PDT 2018
ERROR [Thread-8] (ErrorHandlerFactory.java:84) - White spaces are required between publicId and systemId.

**Comment by DanBerrios** [comment]
I'm wondering if this is an issue with the way imported ontologies are being served by purl.  Searching the web, this error seems to be associated with an unexpected character at the beginning of served XML files.... Usually the BOM (byte order marker).

**Comment by jamesaoverton** [comment]
@turbomam will try to reproduce this problem. Hande can also help.

**Comment by turbomam** [comment]
I just did the following with TBC SE 5.4.2

- hand-edited all of the OWL file names from `*.owl` to `*.rdf` (from the OS, not the TopBraid application)
- launched TopBraid
- file menu -> import -> project from filesystem
- selected the folder containing entire `obi-ontology/obi` repo
- double clicked on `obi.rdf`

I got seven similar and innocuous looking warnings along these lines

> WARN [ModalContext] (ErrorHandlerFactory.java:92) - [line: 8488, col: 109] {W107} Bad URI: <http://purl.oboInOwllibrary.org/oboInOwl/uberon/core#upper_level> Code: 11/LOWERCASE_PREFERRED in HOST: lowercase is preferred in this component

I didn't get the `ERROR [Thread-8] (ErrorHandlerFactory.java:84) - White spaces are required between publicId and systemId.` error.  Besides those few/minor (?) warnings, everything looks good to me.

I don't do this very often, so maybe I'm overlooking something.

**Comment by DanBerrios** [comment]
@jamesaoverton @turbomam So, why does loading obi.owl in TBC not give the same errors as loading obi-edit.owl?

**Comment by jamesaoverton** [comment]
The edit file has links to a number of import files. The release file is merged — no imports.

**Comment by DanBerrios** [comment]
@jamesaoverton Got it, thanks. So it would seem the way the imports are done is causing the errors.  Are these imports the ones defined in the Ontofox_inputs directory?  If so, it seems they are being served by purl.obolibrary.org.  Maybe the config of that server is causing the error.

**Comment by jamesaoverton** [comment]
It sounds like something in the encoding of one of the imported files. There are internal (OBI) and external (BFO, RO, IAO) imports. I think it's more likely to be one of the external ones. It could even be something that an external import imports.

I'm not sure how to determine which import is the problem except by removing all-but-one of the import statements at a time, loading it, and looking for the error.

**Comment by handemcginty** [comment]
let me know if you need me to pass it on to TBC developers.

**Comment by jamesaoverton** [comment]
Good detective work @DanBerrios. I've been thinking about this since you reported your results, but I haven't come up with a good fix. The problem must be in some layer of HTTP redirection. We have control over some of that with the OBO PURL system, but it's not clear to me what should be changed. I'll keep thinking about it.

**Comment by bpeters42** [comment]
Dan will pass on info to TBC developers; right now no action on the OBI side until we have heard back what the problem could be.

**Comment by DanBerrios** [comment]
Reported to TBC developers @ TopQuadrant

**Comment by jamesaoverton** [comment]
I'm reopening this because it looks like a genuine issue with OBI. In `obi-edit.owl` the `xml:base` has a trailing slash, but TBC wants it to match the `ontologyIRI`: 

```
xml:base="http://purl.obolibrary.org/obo/obi/dev/obi-edit.owl/"
```

When that's fixed this import <http://purl.obolibrary.org/obo/obi/external-byhand.owl> erroneously loads from SourceForge, which is a problem with our PURL config.

**Comment by DanBerrios** [comment]
Yes, here is the entire emailed investigation by Holger @TBC 

I downloaded that file into our latest version, and noticed that it declares a mismatching base URI that includes a trailing '/' character:
     xml:base="http://purl.obolibrary.org/obo/obi/dev/obi-edit.owl/"

As a result, it would ignore the owl:imports which are declared in the owl:Ontology instance (without the '/'). But this is easy to fix by removing the '/' from the xml:base.
It then fails to load the imports with errors such as
[TopBraid Warning] 2019-01-17T10:26:15+1000 - org.topbraid.core: Exception connecting to URL http://purl.obolibrary.org/obo/obi/external-byhand.owl (http://obi.svn.sourceforge.net/svnroot/obi/trunk/src/ontology/branches/external-byhand.owl)
java.io.FileNotFoundException: http://obi.svn.sourceforge.net/svnroot/obi/trunk/src/ontology/branches/external-byhand.owl
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
    at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
    at org.topbraid.core.io.TBIOUtil.openURL(TBIOUtil.java:106)
    at org.topbraid.core.registry.impl.URLRegistry.inspectAndRegister(URLRegistry.java:98)
    at org.topbraid.core.registry.impl.AbstractGraphRegistry.getWebImportsBaseURI(AbstractGraphRegistry.java:233)
    at org.topbraid.core.registry.impl.AbstractGraphRegistry.access$0(AbstractGraphRegistry.java:219)
    at org.topbraid.core.registry.impl.AbstractGraphRegistry$2.map1(AbstractGraphRegistry.java:175)
    at org.topbraid.core.registry.impl.AbstractGraphRegistry$2.map1(AbstractGraphRegistry.java:1)
    at org.topbraid.core.registry.impl.AbstractGraphRegistry.getImportBaseURI(AbstractGraphRegistry.java:213)
    at org.topbraid.core.registry.impl.AbstractGraphRegistry.getImportBaseURI(AbstractGraphRegistry.java:172)
    at org.topbraid.core.io.IO.isContextSensitive(IO.java:635)
    at org.topbraid.core.io.IO.access$0(IO.java:634)
    at org.topbraid.core.io.IO$1.compare(IO.java:183)
    at org.topbraid.core.io.IO$1.compare(IO.java:1)
    at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
    at java.util.TimSort.sort(TimSort.java:220)
    at java.util.Arrays.sort(Arrays.java:1512)
    at java.util.ArrayList.sort(ArrayList.java:1462)
    at java.util.Collections.sort(Collections.java:175)
    at org.topbraid.core.io.IO.getURIsToImport(IO.java:179)
    at org.topbraid.core.io.IO.loadImports(IO.java:675)
    at org.topbraid.core.io.IO.loadImports(IO.java:383)
    at org.topbraidcomposer.core.io.TBCIO.loadImportedModels(TBCIO.java:295)
    at org.topbraidcomposer.core.io.TBCIO$2$1.run(TBCIO.java:405)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: http://obi.svn.sourceforge.net/svnroot/obi/trunk/src/ontology/branches/external-byhand.owl
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
    at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3000)
    at org.topbraid.core.io.TBIOUtil.openURL(TBIOUtil.java:104)
    ... 22 more
and going to that URL indeed produces a Not Found error. So maybe some of the redirects are broken on the OBI site.
I then tried opening the same file with Protege and also get an error that the imports cannot be resolved.
So, my current understanding is that newer TopBraid versions have resolved the original Jena issue, yet a problem remains on the OBI site itself.
Holger

**Comment by jamesaoverton** [comment]
@DanBerrios I believe that I fixed this with PR #992. Please take a look

**Comment by DanBerrios** [comment]
@jamesaoverton I still see the same listed errors when I try to load obi-edit.owl (master) in TBC.

**Comment by DanBerrios** [comment]
@jamesaoverton In my TBC error log, after switching to branch fix-940, I am down to only 2 error messages now:

While reading: http://purl.obolibrary.org/obo/obi/dev/external-byhand.owl from null
org.apache.jena.riot.RiotException: White spaces are required between publicId and systemId.
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:136)
	at org.apache.jena.riot.lang.LangRDFXML$ErrorHandlerBridge.fatalError(LangRDFXML.java:243)
	at com.hp.hpl.jena.rdf.arp.impl.ARPSaxErrorHandler.fatalError(ARPSaxErrorHandler.java:48)
	at com.hp.hpl.jena.rdf.arp.impl.XMLHandler.warning(XMLHandler.java:209)
	at com.hp.hpl.jena.rdf.arp.impl.XMLHandler.fatalError(XMLHandler.java:239)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.scanExternalID(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl.scanDoctypeDecl(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.hp.hpl.jena.rdf.arp.impl.RDFXMLParser.parse(RDFXMLParser.java:151)
	at com.hp.hpl.jena.rdf.arp.ARP.load(ARP.java:119)
	at org.apache.jena.riot.lang.LangRDFXML.parse(LangRDFXML.java:142)
	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTFactoryImpl$1.read(RDFParserRegistry.java:142)
	at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:818)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:258)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:244)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:69)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:274)
	at org.topbraid.core.registry.GraphSource.loadModel(GraphSource.java:170)
	at org.topbraid.core.registry.GraphSource.loadPhysicalSource(GraphSource.java:138)
	at org.topbraid.core.registry.GraphSource.loadGraph(GraphSource.java:88)
	at org.topbraid.core.io.IO.loadAndRegister(IO.java:321)
	at org.topbraid.core.io.IO.load(IO.java:293)
	at org.topbraid.core.io.IO.loadImports(IO.java:689)
	at org.topbraid.core.io.IO.loadImports(IO.java:366)
	at org.topbraidcomposer.core.io.TBCIO.loadImportedModels(TBCIO.java:318)
	at org.topbraidcomposer.core.io.TBCIO$2$1.run(TBCIO.java:424)
	at java.lang.Thread.run(Thread.java:745)

ERROR [Thread-8] (ErrorHandlerFactory.java:84) - White spaces are required between publicId and systemId.

Is there something inside external-byhand file that is triggering these remaining 2 errors?  Seems like it can't find or read that URL still...

At least the many other error messages went away...

**Comment by turbomam** [comment]
Using tbcme-6.2.0.v20190329-1031-win32.win32.x86_64 (beta/demo)

I was able to open the content at http://purl.obolibrary.org/obo/obi.owl in TBC using the following technique.  I wasn't able to load the same content using other approaches, or `obi-edit.owl` using any approach, but I haven't tried every permutation of settings yet.

- create fresh TBC workspace
- create new general project
- download http://purl.obolibrary.org/obo/obi.owl to local filesystem
- rename to obi.rdf
- move into project folder from second step
- refresh folder within TBC
- double click on obi.rdf in TBC project explorer 

The TURBO merged release also works with this approach, and also by downloading from the web **within TBC** (import -> topbraid composer -> import RDF from web-> https://raw.githubusercontent.com/PennTURBO/Turbo-Ontology/master/ontologies/turbo_merged.owl; set target filename to `turbo_merged.rdf`)

I was not able to import the TURBO development ontology, as an eclipse project, from a git-managed folder on local filesystem 

Try OBI release import over http **within TBC**
- http://purl.obolibrary.org/obo/obi.owl -> obi.rdf

```
!ENTRY org.topbraid.eclipsex 4 0 2019-05-28 10:42:49.148
!MESSAGE ERROR [ModalContext] (ErrorHandlerFactory.java:101) - [line: 1, col: 50] White spaces are required between publicId and systemId.
```

Loading obi-edit.owl from a local git folder leads to many errors

**Comment by jamesaoverton** [comment]
Thanks @turbomam. The problem was always with `obi-edit.owl` not the released `obi.owl`.

@rctauber just merged #992, and @DanBerrios told me that it reduces the number of errors seen in TopBraid.

@DanBerrios Are you using the latest TopBraid? Holger seemed to be saying that the RiotException was solved by TopBraid updating its Apache Jena dependency.

**Comment by jamesaoverton** [comment]
@DanBerrios Is this still an issue?
